name: conscript_curator
version: 0.1.1
description: >
  Conscript Curator: Weekly Example Sentence Bot for Discord Guild “Mucos: Museum of Constructed Scripts (Conscript Musium)”
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://kiita.migdal.jp/Mucos/Curator
repository: https://github.com/CL-KIITA/Conscript_Curator
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  nyxx: ^6.7.0
  yaml: ^3.1.3
  gsheets: ^0.5.0
  color: ^3.0.0
  cron: ^0.6.2
  week_of_year: ^2.2.0
  timezone: ^0.10.1
  intl: ^0.20.2
  sealed_languages: ^2.3.0
executables:
  curator:
topics:
  - bot
  - discord
  - nyxx
  - Conscript_Musium
  - Example_Sentence
publish_to: none