external type Integer: !native
external type String: !native
external type Snowflake: Snowflake Integer

[#General]
name: @String 例文キュレーター
on: @String AlmaLinux
locale: @String ja_JP

[#Discord]
-- Guild for Bot Running
guild: Snowflake 1145714050676817951
-- Staff Role in the Guild
staff: Snowflake 1309145453241303071
-- Channel for to Send Example Sentence
example: Snowflake !!

[#Spreadsheet]
-- spreadsheet id for Form Answers
form: @String !!
-- spreadsheet id for Database Using
db: @String !!

[#Chrono]
-- cron schedule
cron: @String "0 7 * * 1"
-- timezone for setting
tz: @String "Asia/Tokyo"