#proto core {
  @external type Integer: !native
  @external type Pointed: !native
  @external type String: !native
  @external type DateTime: DateTime!parse &String | DateTime!stamp &Integer | DateTime &Integer &Integer &Integer &Integer &Integer &Integer &Integer &Integer
  @external type Snowflake: Snowflake &Integer
  @external type Locale: Locale!parse &String | Locale &String &String
  @external type TimeZone: TimeZone!parse &String | TimeZone &String &String | TimeZone!byOffset &Integer &Integer
}

[#General]
name: @String 例文キュレーター
title: @String 今週の例文
on: @String AlmaLinux
locale: Locale ja_JP
homepage: Uri!parse !!
articles: Uri!parse !!
icon: Uri!parse !!

[#Discord]
-- Guild for Bot Running
guild: Snowflake 1145714050676817951
-- Staff Role in the Guild
staff: Snowflake 1309145453241303071
-- Channel for to Send Example Sentence
example: Snowflake !!

[#Spreadsheet]
-- Spreadsheet Id for Form Answers
form: @String !!
-- Spreadsheet Id for Database Using
db: @String !!
-- Name of Sheet for Using on Database Spreadsheet
name: @String !!

[#Chrono]
-- cron schedule
cron: @String "0 7 * * 1"
-- timezone for setting
tz: TimeZone Asia/Tokyo